name: learn_dart_apps
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

publish_to: none

dependencies:
  create_dart_library:
    git:
      url: https://github.com/aprxty3/create_dart_library.git
      ref: 1.5.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
